# Generated by Django 6.0.4 on 2026-05-01 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber_name", models.CharField(max_length=255)),
                ("subscription_plan", models.CharField(max_length=255)),
                ("subscription_cost", models.FloatField()),
                ("paypal_subscription_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "subscription2customuser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customuser2subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
